version: "3"
services:
  doge-cool:
    image: doge-cool:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"
